[theme]
base = "dark"                            # Dark mode is a must for that neon glow ✨
primaryColor = "#00ffe0"                 # Aqua neon for buttons & highlights 💧
backgroundColor = "#0f0f1a"              # Deep dark background for high contrast 🌌
secondaryBackgroundColor = "#1a1a2e"     # Slightly lighter dark shade for cards 🎴
textColor = "#f0f0f0"                    # Bright text on dark bg 🌟
font = "sans serif"                      # Clean, modern sans-serif font
